java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter s1 2     at com.wj.ktutils.HttpRequestsKt$httpDU$1.onFailure(SourceFile)